### ISSUE TITLE
Calculating ratio of products without overflow/underflow

### ISSUE THREAD

**Issue by ajt60gaibb** [cgyurgyik/EigenvectorsFromEigenvalues#1]
Consider, the following MATLAB code: 
```
prod( 1 - (2:10000) )/prod( 1 - (3:10001))
ans =
   NaN
```
which happens due to overflow and underflow issues. (The denominator and numerator are both equally huge.) Instead, it is better to do the mathematically equivalent calculation:
```
prod( (1 - (2:10000) ) ./ ( 1 - (3:10001) ) )
ans =
     9.999999999999994e-05
```
Hence, why I did this: 
https://github.com/cgyurgyik/EigenvectorsFromEigenvalues/blob/66d594c55375ff7e4d6cd76df174fe4b78a0694b/GetEigenvectorFromEigenvalues.m#L29

**Comment by cgyurgyik** [comment]
LGTM.
